modLoader="javafml" #mandatory

loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"

issueTrackerURL="" #optional

[[mods]] #mandatory

modId="webdisplays" #mandatory

version="2.0.1-1.20.1" #mandatory

displayName="WebDisplays" #mandatory

displayURL="https://github.com/CinemaMod/webdisplays" #optional

logoFile= "" #optional

credits="" #optional

authors="GiantLuigi4, ds58, Mysticpasta1, montoyo, WaterPicker" #optional

description='''
'''

[[dependencies.webdisplays]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.webdisplays]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.webdisplays]]
modId="mcef"
mandatory=true
versionRange="[2.0.0+1.20.1, )"
ordering="NONE"
side="BOTH"
